### ISSUE TITLE
Slugs broken?

### ISSUE THREAD

**Issue by delcypher** [klee/klee.github.io#16]
I was taking a look what the `slug` page attribute was doing. It looks kind of broken.

The file `_includes/nav/main.html` gives hints at what the intention was, e.g.

``` html
<nav class="navdrawer-container promote-layer" role="navigation">
  <h4>Navigation</h3>
  <ul>
    <li{% if page.slug == "getting-started" %} class="active"{% endif %}>
      <a href="{{ site.baseurl }}/getting-started">Getting Started</a>
    </li>
    <li{% if page.slug == "documentation" %} class="active"{% endif %}>
      <a href="{{ site.baseurl }}/docs">Documentation</a>
    </li>
    <li{% if page.slug == "tutorials" %} class="active"{% endif %}>
      <a href="{{ site.baseurl }}/tutorials">Tutorials</a>
    </li>
    <li{% if page.slug == "publications" %} class="active"{% endif %}>
      <a href="{{ site.baseurl }}/publications">Publications</a>
    </li>
    <li{% if page.slug == "projects" %} class="active"{% endif %}>
      <a href="{{ site.baseurl }}/projects">Projects</a>
    </li>
    <li{% if page.slug == "getting-involved" %} class="active"{% endif %}>
      <a href="{{ site.baseurl }}/getting-involved">Getting Involved</a>
    </li>
  </ul>
</nav>
```

There seem to be two problems with this
- We have incorrect named `slugs` for several pages (e.g. `docs/coreutils-experiments.md`)
- The `active` class isn't used properly in the CSS. The file `css/main.scss` has

``` css
.navdrawer-container ul li a:active {
  background-color: rgba(255, 255, 255, 0.4);
}
```

but to work (at least for chromium 46.0.2490.80) the CSS needs to be

``` css
.navdrawer-container ul li a.active {
  background-color: rgba(255, 255, 255, 0.4);
}
```

@ccadar @petrhosek Thoughts?
